name: Deploy to Public Repository

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci

    - name: Create .env file from secrets
      run: |
        echo "VITE_AUTH0_DOMAIN=${{ secrets.VITE_AUTH0_DOMAIN }}" > .env
        echo "VITE_AUTH0_CLIENT_ID=${{ secrets.VITE_AUTH0_CLIENT_ID }}" >> .env
        if [ "${{ secrets.VITE_AUTH0_AUDIENCE }}" != "" ]; then
          echo "VITE_AUTH0_AUDIENCE=${{ secrets.VITE_AUTH0_AUDIENCE }}" >> .env
        fi
        
        # Also create .env.production for production builds
        echo "VITE_AUTH0_DOMAIN=${{ secrets.VITE_AUTH0_DOMAIN }}" > .env.production
        echo "VITE_AUTH0_CLIENT_ID=${{ secrets.VITE_AUTH0_CLIENT_ID }}" >> .env.production
        if [ "${{ secrets.VITE_AUTH0_AUDIENCE }}" != "" ]; then
          echo "VITE_AUTH0_AUDIENCE=${{ secrets.VITE_AUTH0_AUDIENCE }}" >> .env.production
        fi
        
        # Debug: show what we created
        echo "Created .env file:"
        cat .env
        echo "Created .env.production file:"
        cat .env.production
      
    - name: Debug .env file
      run: |
        echo "Debugging .env file contents:";
        cat .env;
        echo "Debugging .env.production file contents:";
        cat .env.production;

    - name: Build
      run: |
        echo "Building with environment:"
        echo "NODE_ENV=$NODE_ENV"
        npm run build
        
        # Debug: check if environment variables made it into the build
        echo "Checking for Auth0 config in built files:"
        grep -r "merajmunshi" dist/ || echo "No Auth0 domain found in build"
        grep -r "wetVbccRWFxGMtiWEfAI9XGFZnWRj4Gd" dist/ || echo "No Auth0 client ID found in build"
      
    - name: Deploy to Public Repository
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        personal_token: ${{ secrets.DEPLOY_TOKEN }}
        external_repository: merajmunshiofficial/dsamentor-deploy
        publish_dir: ./dist
        publish_branch: main
        force_orphan: true
