name: Deploy to Public Repository

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci

    - name: Create .env files from secrets
      run: |
        # Create .env and .env.production files
        echo "Creating environment files from secrets..."
        echo "VITE_AUTH0_DOMAIN=${{ secrets.VITE_AUTH0_DOMAIN }}" > .env
        echo "VITE_AUTH0_CLIENT_ID=${{ secrets.VITE_AUTH0_CLIENT_ID }}" >> .env
        if [ "${{ secrets.VITE_AUTH0_AUDIENCE }}" != "" ]; then
          echo "VITE_AUTH0_AUDIENCE=${{ secrets.VITE_AUTH0_AUDIENCE }}" >> .env
        fi
        if [ "${{ secrets.VITE_PROD_CALLBACK_URL }}" != "" ]; then
          echo "VITE_PROD_CALLBACK_URL=${{ secrets.VITE_PROD_CALLBACK_URL }}" >> .env
        fi
        
        # Copy .env to .env.production
        cp .env .env.production
        
        # Verify files exist without displaying contents
        if [ -f ".env" ] && [ -f ".env.production" ]; then
          echo "✅ Environment files created successfully"
        else
          echo "❌ Failed to create environment files"
          exit 1
        fi

    - name: Build
      run: |
        echo "🔨 Starting production build..."
        npm run build
        
        # Security check: Ensure no sensitive data in build
        echo "🔍 Running security checks on build files..."
        if grep -r "auth0\.com" dist/; then
          echo "⚠️ Warning: Found potential Auth0 domain in build files"
          exit 1
        fi
        if grep -r "sk-[a-zA-Z0-9]\{32,\}" dist/; then
          echo "⚠️ Warning: Found potential API key in build files"
          exit 1
        fi
        echo "✅ Security checks passed"
      
    - name: Deploy to Public Repository
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        personal_token: ${{ secrets.DEPLOY_TOKEN }}
        external_repository: merajmunshiofficial/dsamentor-deploy
        publish_dir: ./dist
        publish_branch: main
        force_orphan: true
